/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const RoutedTableLazyImport = createFileRoute('/routed-table')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const RoutedTableLazyRoute = RoutedTableLazyImport.update({
  path: '/routed-table',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/routed-table.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/routed-table': {
      id: '/routed-table'
      path: '/routed-table'
      fullPath: '/routed-table'
      preLoaderRoute: typeof RoutedTableLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  RoutedTableLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/routed-table"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/routed-table": {
      "filePath": "routed-table.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
