/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as RoutedTableMeasurementIdIndexImport } from './routes/routed-table/$measurementId/index'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const RoutedTableIndexLazyImport = createFileRoute('/routed-table/')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const RoutedTableIndexLazyRoute = RoutedTableIndexLazyImport.update({
  path: '/routed-table/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/routed-table/index.lazy').then((d) => d.Route),
)

const RoutedTableMeasurementIdIndexRoute =
  RoutedTableMeasurementIdIndexImport.update({
    path: '/routed-table/$measurementId/',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/routed-table/': {
      id: '/routed-table/'
      path: '/routed-table'
      fullPath: '/routed-table'
      preLoaderRoute: typeof RoutedTableIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/routed-table/$measurementId/': {
      id: '/routed-table/$measurementId/'
      path: '/routed-table/$measurementId'
      fullPath: '/routed-table/$measurementId'
      preLoaderRoute: typeof RoutedTableMeasurementIdIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  RoutedTableIndexLazyRoute,
  RoutedTableMeasurementIdIndexRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/routed-table/",
        "/routed-table/$measurementId/"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/routed-table/": {
      "filePath": "routed-table/index.lazy.tsx"
    },
    "/routed-table/$measurementId/": {
      "filePath": "routed-table/$measurementId/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
